services:
  - type: web
    name: bubbyberryfortress-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: bubbyberryfortress-client
    env: node
    plan: free
    buildCommand: cd client && npm install
    startCommand: npm run start:client