services:
  - type: web
    name: bubbyberryfortress-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: npm run start:server
  - type: web
    name: bubbyberryfortress-client
    env: node
    plan: free
    buildCommand: cd client && npm install
    startCommand: npm run start:client
