services:
 # Start MaSter Server
  - type: web
    name: bubbyberryfortress-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:server
# Start Game Client Server
  - type: web
    name: bubbyberryfortress-client
    env: node
    plan: free
    buildCommand: cd client && npm install
    startCommand: npm run start:client
