services:
  - type: web
    name: bubbyberryfortress-server
    env: node
    plan: free
    buildCommand: npm install && npm build
    startCommand: npm run start:server
  - type: web
    name: bubbyberryfortress-client
    env: node
    plan: free
    buildCommand: cd client && npm build && npm install
    startCommand: npm run start:client
