services:
  - type: web
    name: bubbyberryfortress-server
    env: node
    plan: free
    buildCommand: cd src && npm install && npm run build
    startCommand: npm run start:server
  - type: web
    name: bubbyberryfortress-client
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: npm run start:client
